---
language: ruby
cache: bundler
script:
    - "bundle exec rake validate lint spec SPEC_OPTS='--format documentation' "
    - "gem list;  "
matrix:
  fast_finish: true
  include:
#  - rvm: 2.3.1
#    dist: trusty
#    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true STRICT_VARIABLES="yes"
#    script: bundle exec rake beaker
#    services: docker
#    sudo: required
#  - rvm: 2.3.1
#    dist: trusty
#    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true
#    script: bundle exec rake beaker
#    services: docker
#    sudo: required
#  - rvm: 2.3.1
#    dist: trusty
#    env: BEAKER_set=ubuntu-16.04 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true
#    script: bundle exec rake beaker
#    services: docker
#    sudo: required
#  - rvm: 2.3.1
#    dist: trusty
#    env: BEAKER_set=centos-7 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true
#    script: bundle exec rake beaker
#    services: docker
#    sudo: required
  - rvm: 2.1.6
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.5" STRICT_VARIABLES="yes"
  - rvm: 2.1.6
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.5" 
  - rvm: 2.1.6
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.8" STRICT_VARIABLES="yes"
  - rvm: 2.1.6
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.8"
  - rvm: 1.9.3
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.8"
notifications:
  email: false
